services:
  profile_db:
    image: postgres:16
    container_name: fit_profile_db
    restart: unless-stopped
    ports:
      - "5440:5432"
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qewr
      POSTGRES_DB: profile_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  keycloak_db:
    image: postgres:16
    container_name: keycloak_db
    restart: unless-stopped
    ports:
      - "5441:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    command:
      - start-dev
      - --import-realm
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      # Пробрасываем наш JSON файл в папку импорта Keycloak
      - ./fitassistant-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "5442:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy

volumes:
  profile_postgres_data:
  keycloak_postgres_data: